---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: harrijin-test-redis-data
    labels:
        username: harrijin
        env: test
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: rbd
    resources:
        requests:
            storage: 1Gi
