---
apiVersion: v1
kind: Service
metadata:
    name: harrijin-test-redis-service
    labels:
        username: harrijin
        env: test
spec:
    type: ClusterIP
    selector:
        app: harrijin-test-redis
    ports:
      - name: harrijin-test-redis
        port: 6379
        targetPort: 6379

