version: '3'
services:
    web:
        build: .
        container_name: flask_web_hqj59
        ports:
            - 5013:5000
    redis:
        image: redis:latest
        ports:
            - 6393:6379
        volumes:
            - ./config/redis.conf:/redis.conf
            - ./data/:/data
        command: [ "redis-server", "/redis.conf"  ]